export interface QuestionOption {
  label: string;
  score: number;
}

export interface BaseQuestion {
  id: string;
  section: string;
  text: string;
  subtitle?: string;
}

export interface SingleQuestion extends BaseQuestion {
  type: "single";
  options: QuestionOption[];
}

export interface SliderQuestion extends BaseQuestion {
  type: "slider";
  min: number;
  max: number;
  multiplier: number;
}

export type Question = SingleQuestion | SliderQuestion;

export interface SectionData {
  id: string;
  label: string;
  maxScore: number;
  questionIds: string[];
  recommendations: {
    high: string;
    mid: string;
    low: string;
  };
}

export const questions: Question[] = [
  // ── REVENUE & BOOK STRUCTURE ──
  { id: "q1", section: "Revenue & Book Structure", text: "What was your total annual gross revenue over the trailing 12 months?", subtitle: "Advisory fees + planning fees + insurance + commissions combined", type: "single", options: [{ label: "Under $300K", score: 0 }, { label: "$300K – $500K", score: 3 }, { label: "$500K – $1M", score: 5 }, { label: "$1M – $2M", score: 7 }, { label: "$2M+", score: 7 }] },
  { id: "q2", section: "Revenue & Book Structure", text: "What percentage of your revenue is recurring (advisory fees, trails, 12b-1s)?", subtitle: "This is the single most important valuation driver in open-market transactions", type: "single", options: [{ label: "Under 40%", score: 1 }, { label: "40–65%", score: 3 }, { label: "65–85%", score: 5 }, { label: "85%+", score: 7 }] },
  { id: "q3", section: "Revenue & Book Structure", text: "What percentage of your total revenue is generated by your top 10% of clients?", subtitle: "Measures concentration risk — a hidden vulnerability in most books", type: "single", options: [{ label: "Over 50%", score: 1 }, { label: "35–50%", score: 3 }, { label: "25–35%", score: 5 }, { label: "Under 25%", score: 7 }] },
  { id: "q4", section: "Revenue & Book Structure", text: "What is your approximate average revenue per client household?", subtitle: "Open-market benchmark for fee-based practices is ~$9,400/client", type: "single", options: [{ label: "Under $3,000", score: 1 }, { label: "$3,000 – $6,000", score: 3 }, { label: "$6,000 – $10,000", score: 5 }, { label: "$10,000+", score: 7 }] },
  { id: "q5", section: "Revenue & Book Structure", text: "What is your total expense ratio (excluding owner compensation)?", subtitle: "Market benchmark is ~39% — lower is better for valuation", type: "single", options: [{ label: "Over 45%", score: 1 }, { label: "35–45%", score: 3 }, { label: "25–35%", score: 5 }, { label: "Under 25%", score: 7 }] },
  { id: "q6", section: "Revenue & Book Structure", text: "How many client households do you currently serve?", type: "single", options: [{ label: "Under 50", score: 3 }, { label: "50 – 100", score: 5 }, { label: "100 – 200", score: 7 }, { label: "200+", score: 5 }] },
  // ── CLIENT QUALITY & DEMOGRAPHICS ──
  { id: "q7", section: "Client Quality & Demographics", text: "What percentage of your clients are in the 'prime age' range (51–70)?", subtitle: "Peak earning and saving cycle — highest valuation weight per FP Transitions benchmarks", type: "single", options: [{ label: "Under 15%", score: 2 }, { label: "15–30%", score: 4 }, { label: "30–50%", score: 7 }, { label: "Over 50%", score: 5 }] },
  { id: "q8", section: "Client Quality & Demographics", text: "What percentage of your clients are over age 70?", subtitle: "Higher % = distribution phase risk, unless offset by multi-generational planning", type: "single", options: [{ label: "Over 25%", score: 1 }, { label: "15–25%", score: 3 }, { label: "5–15%", score: 5 }, { label: "Under 5%", score: 7 }] },
  { id: "q9", section: "Client Quality & Demographics", text: "Do you actively provide multi-generational planning (serving children/grandchildren of senior clients)?", subtitle: "Mitigates mortality risk and extends client lifetime value", type: "single", options: [{ label: "Yes — 30%+ of senior client assets are multi-gen", score: 7 }, { label: "Some — beginning to formalize", score: 4 }, { label: "No", score: 1 }] },
  { id: "q10", section: "Client Quality & Demographics", text: "What is your average client tenure (years with your firm)?", subtitle: "FP Transitions benchmark: clients with 7+ years have significantly higher retention in transition", type: "single", options: [{ label: "Under 3 years", score: 1 }, { label: "3–5 years", score: 3 }, { label: "5–8 years", score: 5 }, { label: "8+ years", score: 7 }] },
  { id: "q11", section: "Client Quality & Demographics", text: "What is the average affluence level of your clients (AUM per household)?", subtitle: "Open-market benchmark: ~$1.3M per household", type: "single", options: [{ label: "Under $250K", score: 1 }, { label: "$250K – $500K", score: 3 }, { label: "$500K – $1M", score: 5 }, { label: "$1M+", score: 7 }] },
  { id: "q12", section: "Client Quality & Demographics", text: "What has been your new client growth rate over the past 12 months?", subtitle: "Measures organic growth potential — critical for buyer confidence", type: "single", options: [{ label: "Negative or flat", score: 0 }, { label: "1–10%", score: 3 }, { label: "10–25%", score: 5 }, { label: "25%+", score: 7 }] },
  // ── CLIENT PORTABILITY ──
  { id: "q13", section: "Client Portability", text: "How would you describe your primary client relationships?", type: "single", options: [{ label: "Deep personal relationships — they follow me, not the brand", score: 7 }, { label: "Strong but some loyalty to the firm's brand/platform", score: 4 }, { label: "Mostly transactional or firm-dependent", score: 1 }] },
  { id: "q14", section: "Client Portability", text: "How many of your top 20 clients have you personally onboarded and managed from day one?", type: "single", options: [{ label: "18–20", score: 7 }, { label: "12–17", score: 5 }, { label: "6–11", score: 3 }, { label: "Under 6", score: 1 }] },
  { id: "q15", section: "Client Portability", text: "How do your top 10% of clients (by revenue) compare in tenure to your overall book?", subtitle: "Longer tenure on largest clients = lower transition risk at the top of the revenue stack", type: "single", options: [{ label: "Significantly longer tenure than average", score: 7 }, { label: "About the same", score: 4 }, { label: "Shorter tenure (newer, larger clients)", score: 1 }] },
  { id: "q16", section: "Client Portability", text: "Are your clients concentrated at a single custodian, or diversified?", type: "single", options: [{ label: "Concentrated at current firm's proprietary custodian", score: 2 }, { label: "Single independent custodian (Schwab, Fidelity, Altruist, etc.)", score: 5 }, { label: "Diversified across multiple custodians", score: 7 }] },
  // ── INTENT & TIMING ──
  { id: "q17", section: "Intent & Timing", text: "When are you realistically considering independence?", type: "single", options: [{ label: "Within 3 months", score: 7 }, { label: "3–6 months", score: 7 }, { label: "6–12 months", score: 4 }, { label: "12+ months", score: 2 }, { label: "Exploring only", score: 1 }] },
  { id: "q18", section: "Intent & Timing", text: "How many years has your practice been operating?", subtitle: "FP Transitions benchmark: practices under 5 years face higher transition risk", type: "single", options: [{ label: "Under 3 years", score: 1 }, { label: "3–5 years", score: 3 }, { label: "5–10 years", score: 5 }, { label: "10+ years", score: 7 }] },
  { id: "q19", section: "Intent & Timing", text: "Are you currently under a retention package or forgivable loan?", type: "single", options: [{ label: "No", score: 7 }, { label: "Yes, under $100K remaining", score: 3 }, { label: "Yes, $100K+ remaining", score: 1 }] },
  { id: "q20", section: "Intent & Timing", text: "Which independence structure are you evaluating?", type: "single", options: [{ label: "Full RIA (own ADV)", score: 7 }, { label: "Hybrid RIA + BD", score: 5 }, { label: "IAR under another RIA", score: 3 }, { label: "Unsure", score: 1 }] },
  // ── FINANCIAL READINESS ──
  { id: "q21", section: "Financial Readiness", text: "If revenue declined 25% for 6–9 months during transition, could you maintain stability?", type: "single", options: [{ label: "Yes — no lifestyle changes needed", score: 7 }, { label: "Yes, with meaningful but manageable adjustments", score: 4 }, { label: "No — it would create real hardship", score: 0 }] },
  { id: "q22", section: "Financial Readiness", text: "How much personal liquidity do you currently maintain?", type: "single", options: [{ label: "Under 6 months of expenses", score: 1 }, { label: "6–12 months", score: 4 }, { label: "12–18 months", score: 6 }, { label: "18+ months", score: 7 }] },
  { id: "q23", section: "Financial Readiness", text: "Have you modeled the startup costs of your target independent structure?", subtitle: "Technology, compliance, E&O insurance, custodial setup, licensing, office", type: "single", options: [{ label: "Yes — detailed projections with line items", score: 7 }, { label: "Roughly — ballpark estimates", score: 4 }, { label: "No — haven't started", score: 1 }] },
  { id: "q24", section: "Financial Readiness", text: "Have you had your current practice valued by a qualified appraiser?", subtitle: "Knowing your enterprise value is foundational to any transition strategy", type: "single", options: [{ label: "Yes — formal valuation within last 12 months", score: 7 }, { label: "Informal estimate or outdated valuation", score: 3 }, { label: "No", score: 1 }] },
  // ── PSYCHOLOGICAL READINESS ──
  { id: "q25", section: "Psychological Readiness", text: "When facing uncertainty, you typically:", type: "single", options: [{ label: "Make decisive moves with incomplete information", score: 7 }, { label: "Gather more data before acting", score: 4 }, { label: "Delay action to reduce risk", score: 1 }] },
  { id: "q26", section: "Psychological Readiness", text: "When challenged directly about blind spots in your leadership, you tend to:", type: "single", options: [{ label: "Welcome it — I actively seek it", score: 7 }, { label: "Tolerate it", score: 4 }, { label: "Resist or deflect it", score: 0 }] },
  { id: "q27", section: "Psychological Readiness", text: "If a key client indicated they might not follow you, your likely internal response:", type: "single", options: [{ label: "Strategic recalibration — adjust the plan", score: 7 }, { label: "Frustration — but I'd push through", score: 3 }, { label: "Self-doubt — question the whole move", score: 0 }] },
  { id: "q28", section: "Psychological Readiness", text: "How aligned is your spouse or partner regarding independence?", type: "single", options: [{ label: "Fully aligned — active supporter", score: 7 }, { label: "Supportive but has concerns", score: 4 }, { label: "Uncertain or uninformed", score: 2 }, { label: "Resistant", score: 0 }] },
  { id: "q29", section: "Psychological Readiness", text: "Comfort with temporary income volatility and public uncertainty (1–10):", type: "slider", min: 1, max: 10, multiplier: 0.7 },
  { id: "q30", section: "Psychological Readiness", text: "Today, you primarily see yourself as:", type: "single", options: [{ label: "A high-performing advisor", score: 3 }, { label: "A business owner", score: 5 }, { label: "A founder building enterprise value", score: 7 }, { label: "Unsure", score: 1 }] },
  // ── OPERATOR DISCIPLINE ──
  { id: "q31", section: "Operator Discipline", text: "Do you currently operate with documented SOPs for client onboarding, service, and compliance?", type: "single", options: [{ label: "Yes, fully documented and systematized", score: 7 }, { label: "Partially documented", score: 4 }, { label: "No", score: 0 }] },
  { id: "q32", section: "Operator Discipline", text: "How frequently do you review business performance metrics (revenue, client growth, retention)?", type: "single", options: [{ label: "Weekly", score: 7 }, { label: "Monthly", score: 5 }, { label: "Quarterly", score: 3 }, { label: "Rarely", score: 0 }] },
  { id: "q33", section: "Operator Discipline", text: "Do you currently use a structured operating system (EOS, 12 Week Year, etc.)?", type: "single", options: [{ label: "Yes — actively implementing one", score: 7 }, { label: "Familiar but not implementing", score: 3 }, { label: "No", score: 1 }] },
  { id: "q34", section: "Operator Discipline", text: "Do you have a formal continuity plan (death/disability) in place?", subtitle: "A documented continuity plan reduces Business Continuity Risk and increases valuation", type: "single", options: [{ label: "Yes — documented and funded", score: 7 }, { label: "In progress", score: 4 }, { label: "No", score: 0 }] },
  { id: "q35", section: "Operator Discipline", text: "Do you have non-compete/non-solicitation agreements in place with licensed employees?", subtitle: "Reduces buyer risk and increases enterprise value in any transition scenario", type: "single", options: [{ label: "Yes — all licensed employees", score: 7 }, { label: "Some employees", score: 4 }, { label: "No employees / No agreements", score: 1 }] },
  // ── TECHNOLOGY & INFRASTRUCTURE ──
  { id: "q36", section: "Technology & Infrastructure", text: "Rate your current technology stack:", subtitle: "CRM, portfolio management, document storage, billing, client portal, video conferencing", type: "single", options: [{ label: "Advanced — non-proprietary CRM, electronic billing, document scanning, portfolio software, client portal", score: 7 }, { label: "Competent — using most tools my firm provides", score: 4 }, { label: "Basic — rely on staff for most tech, minimal systems", score: 1 }] },
  { id: "q37", section: "Technology & Infrastructure", text: "Have you researched custodial platforms (Schwab, Fidelity, Pershing, Altruist)?", type: "single", options: [{ label: "Yes — active conversations with 2+ custodians", score: 7 }, { label: "Some initial research", score: 4 }, { label: "No", score: 1 }] },
  { id: "q38", section: "Technology & Infrastructure", text: "How dependent are you on your current firm's proprietary tools or products?", subtitle: "Proprietary product dependency increases Business Continuity Risk and lowers portability", type: "single", options: [{ label: "Not at all — everything is open architecture", score: 7 }, { label: "Somewhat — a few proprietary products", score: 4 }, { label: "Heavily — most clients are in firm products", score: 1 }] },
  { id: "q39", section: "Technology & Infrastructure", text: "Where do you primarily meet with clients?", subtitle: "Virtual-first practices have broader buyer appeal and lower geographic transition risk", type: "single", options: [{ label: "90%+ video conferencing", score: 7 }, { label: "Mix of virtual and in-person", score: 5 }, { label: "Primarily in-person at my office", score: 3 }, { label: "Primarily at client homes/offices", score: 2 }] },
  // ── COMMITMENT & COACHABILITY ──
  { id: "q40", section: "Commitment & Coachability", text: "Are you prepared to receive direct, unfiltered feedback — including that independence may not be right for you?", type: "single", options: [{ label: "Yes — that's exactly what I'm paying for", score: 7 }, { label: "I think so", score: 3 }, { label: "Not sure", score: 0 }] },
  { id: "q41", section: "Commitment & Coachability", text: "If independence isn't viable within 12 months, would you invest in strengthening leadership, team, and operations anyway?", type: "single", options: [{ label: "Yes — building enterprise value has ROI regardless", score: 7 }, { label: "Maybe", score: 3 }, { label: "No — I only want help with the breakaway itself", score: 0 }] },
  { id: "q42", section: "Commitment & Coachability", text: "If you transition, who would likely move with you?", type: "single", options: [{ label: "My full team is committed", score: 7 }, { label: "Most of my team, with some uncertainty", score: 5 }, { label: "One key person, maybe", score: 3 }, { label: "I'd be starting solo", score: 2 }] },
];

export const sections: SectionData[] = [
  { id: "rev", label: "Revenue & Book Structure", maxScore: 42, questionIds: ["q1","q2","q3","q4","q5","q6"],
    recommendations: {
      high: "Your revenue profile is strong. High recurring revenue, low concentration risk, and healthy per-client economics are the three factors that drive open-market multiples. Your book would attract serious buyer interest if listed today. Action: Maintain your recurring revenue ratio above 85% and continue reducing concentration in your top 10%.",
      mid: "Solid revenue foundation with specific structural gaps. The FP Transitions valuation model weights recurring revenue and concentration risk heavily — these are your highest-ROI improvement areas. Action: Calculate your exact revenue concentration (top 10% of clients as % of total revenue). If it's above 35%, develop a deliberate strategy to grow mid-tier client revenue.",
      low: "Revenue structure needs significant work before independence is viable. Low recurring revenue, high concentration, or thin per-client economics all suppress open-market multiples. Action: Prioritize converting to 85%+ recurring revenue. Build to $500K+ trailing 12-month gross revenue before reconsidering a breakaway."
    }
  },
  { id: "cqd", label: "Client Quality & Demographics", maxScore: 42, questionIds: ["q7","q8","q9","q10","q11","q12"],
    recommendations: {
      high: "Your client demographics and growth profile are strong. A young, growing client base with solid tenure is the Cash Flow Quality profile that drives premium valuations. Action: Formalize your multi-generational planning offering — it's both a retention tool and a valuation multiplier.",
      mid: "Good foundation with demographic or growth gaps. Action: If your 'prime age' (51-70) client percentage is low, focus on increasing wallet share with existing clients through comprehensive planning. If client tenure is short, focus on deepening relationships through quarterly touchpoints.",
      low: "Client quality metrics need attention. Low affluence, short tenure, or unfavorable demographics will suppress both your valuation and buyer demand. Action: Audit your client base — segment by age, tenure, and revenue contribution. Build a 12-month plan to improve average client affluence through strategic prospecting at the $500K+ AUM level."
    }
  },
  { id: "port", label: "Client Portability", maxScore: 28, questionIds: ["q13","q14","q15","q16"],
    recommendations: {
      high: "Your client relationships are advisor-centric, not firm-centric. Your portability profile suggests 90%+ retention is achievable. Action: Begin documenting client contact information and communication preferences outside firm systems.",
      mid: "Portability is probable but not certain. Action: Categorize your top 20 clients into 'will follow,' 'likely,' and 'at risk.' Develop a specific retention strategy for each 'at risk' client.",
      low: "Client dependency on your firm's brand or platform is a major risk. Action: Shift client conversations toward goals-based planning language that emphasizes YOUR value, not the firm's platform."
    }
  },
  { id: "int", label: "Intent & Timing", maxScore: 28, questionIds: ["q17","q18","q19","q20"],
    recommendations: {
      high: "Your timeline is actionable, your practice tenure supports it, and your structural clarity is strong. Action: Begin confidential preparation immediately.",
      mid: "Intent is real, but timing, tenure, or structural constraints may slow execution. Action: If practice tenure is your gap, use the time productively. Resolve any retention package obligations within 60 days.",
      low: "You're in exploration mode. Action: Clarify your 'why' in writing. Use the next 12 months to build practice tenure and structural clarity."
    }
  },
  { id: "fin", label: "Financial Readiness", maxScore: 28, questionIds: ["q21","q22","q23","q24"],
    recommendations: {
      high: "You've built the financial runway to absorb transition volatility. Action: Model three scenarios (best/base/worst) for months 1–12 post-transition, using your valuation as the baseline.",
      mid: "Workable but tight. Action: Build personal liquidity to 12+ months. Get a Revenue Strength Analysis done. Budget $30K-$60K for transition costs.",
      low: "Financial risk is too high for a near-term breakaway. Action: Aggressively build reserves for 12–18 months. Get your practice valued — knowing your enterprise value changes the entire calculus."
    }
  },
  { id: "psy", label: "Psychological Readiness", maxScore: 42, questionIds: ["q25","q26","q27","q28","q29","q30"],
    recommendations: {
      high: "You demonstrate the founder's mindset — decisive under uncertainty, resilient to setback, coachable. The identity shift from 'advisor' to 'business owner building enterprise value' is the hardest dimension to develop and you have it.",
      mid: "Strong in some areas, with specific blind spots. Action: Have an honest conversation with your spouse/partner about worst-case scenarios. Address alignment gaps before they become mid-transition crises.",
      low: "Psychological readiness requires intentional development. Action: Work with a coach on decision-making under uncertainty and identity evolution from 'advisor' to 'CEO.' This is the most common reason advisors delay — and the most fixable."
    }
  },
  { id: "ops", label: "Operator Discipline", maxScore: 35, questionIds: ["q31","q32","q33","q34","q35"],
    recommendations: {
      high: "You operate like a business owner already. Documented SOPs, metrics cadence, continuity planning, and employee non-competes all reduce Business Continuity Risk. Action: Maintain your systems and ensure they're transferable to an independent structure.",
      mid: "Operational gaps exist but are fixable. Action: Implement one structured operating system (12 Week Year or EOS) within 90 days. Get your continuity plan documented. Execute non-compete agreements with all licensed employees.",
      low: "This is your highest-leverage development area. Action: Spend 90 days building foundational habits — weekly metrics reviews, written SOPs for your top 3 processes, a formal continuity plan, and a quarterly planning rhythm."
    }
  },
  { id: "tech", label: "Technology & Infrastructure", maxScore: 28, questionIds: ["q36","q37","q38","q39"],
    recommendations: {
      high: "Your advanced, non-proprietary tech stack means a buyer or successor can complete due diligence faster. Virtual-first practices also have broader geographic buyer appeal. Action: Finalize custodial conversations and negotiate terms before giving notice.",
      mid: "Tech awareness without depth. Action: Schedule discovery calls with 2–3 custodians. Map your current tech stack to independent alternatives. Budget $500–$1,500/month for your independent tech stack.",
      low: "Low technology levels decrease client retention during transitions. Action: Start with the basics — implement a non-proprietary CRM and document scanning. These are table stakes for independence."
    }
  },
  { id: "com", label: "Commitment & Coachability", maxScore: 21, questionIds: ["q40","q41","q42"],
    recommendations: {
      high: "Your openness to feedback and long-term thinking separates you from advisors who break away prematurely. Thinking in terms of 'enterprise value' rather than 'escape velocity' is the right framework.",
      mid: "Commitment is there but contingencies remain. Action: Identify and neutralize the #1 source of resistance in your circle. Have the hard conversation this month.",
      low: "A breakaway without full commitment is a breakaway that fails. Action: Be honest about whether you want independence or just want to escape your current situation. Those are different motivations with different outcomes."
    }
  },
];

export const TOTAL_QUESTIONS = questions.length;
export const MAX_SCORE = sections.reduce((a, s) => a + s.maxScore, 0);

// Benchmarks for comparison (average advisor baselines)
export const benchmarks: Record<string, number> = {
  rev: 52,
  cqd: 48,
  port: 55,
  int: 45,
  fin: 40,
  psy: 50,
  ops: 38,
  tech: 45,
  com: 58,
};
